### ISSUE TITLE
Is it possible to get power on your AirPods yet?

### ISSUE THREAD

**Issue by zhuozhuo** [alpatyev/airPodsTester#1]
Hello, did you get the charge on your AirPods?

**Comment by alpatiev** [comment]
Hi! There is some possibility but it is unfortunately part of the production code. I
'm going to come back here later and make a small api and one class that implements this.

In general, approach looks like this:

```
func peripheral(_ peripheral: CBPeripheral, didDiscoverCharacteristicsFor service: CBService, error: Error?) {
    if let characteristics = service.characteristics {
        for characteristic in characteristics {
            if characteristic.uuid.uuidString == "2A37" {
                peripheral.readValue(for: characteristic)
            }
        }
    }
}

```

**Comment by alpatiev** [comment]
https://github.com/FleXoft/Polar-H7-HRM/blob/master/HRM/ViewController.swift
